query getStations {
  getStations {
    items {
      _id
      name
      slug
      title
      website
      bitrate
      stream
      tags
      # disabled
      dateAdded
      dateUpdated
    }
  }
}
